name: Deploy Django project to PythonAnywhere

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Run PA_UPDATE.sh on server
              env:
                PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
                PA_USERNAME: ${{ secrets.PA_USERNAME }}
              run: |
                curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
                -d "" \
                "https:/www.pythonanywhere.com/api/v0/user/$PA_USERNAME/consoles/" \
                -d "command=/home/$PA_USERNAME/PA_UPDATE.sh"