name: Deploy Django project to PythonAnywhere

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Start PythonAnywhere console
           id: start_console
           run: |
             response=$(curl -X POST \
               -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
               https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/ \
               -d "executable=/bin/bash")
             console_id=$(echo $response | jq -r .id)
             echo "::set-output name=console_id::$console_id"

         - name: Run shell script on PythonAnywhere
           run: |
             curl -X POST \
               -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
               https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/${{ steps.start_console.outputs.console_id }}/send_input/ \
               -d "input=./PA_UPDATE.sh\n"
